"""added is_public in Blog model

Revision ID: 1a4d1f034c48
Revises: fdda1472b465
Create Date: 2025-08-14 19:57:12.284317

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a4d1f034c48"
down_revision: Union[str, Sequence[str], None] = "fdda1472b465"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blog", schema=None) as batch_op:
        sa.Column(
            "is_public",
            sa.Boolean(),
            nullable=False,
            server_default=sa.sql.expression.true(),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blog", schema=None) as batch_op:
        batch_op.drop_column("is_public")

    # ### end Alembic commands ###
