"""Added cascade on delete

Revision ID: 363801c14309
Revises:
Create Date: 2025-11-08 11:28:32.894442

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "363801c14309"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blog", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("blog_author_fkey"), type_="foreignkey")
        batch_op.create_foreign_key(
            None, "user", ["author"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("bloglikelink", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("bloglikelink_blog_id_fkey"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("bloglikelink_user_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "user", ["user_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            None, "blog", ["blog_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("blogtaglink", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("blogtaglink_blog_id_fkey"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("blogtaglink_tag_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(None, "tag", ["tag_id"], ["id"], ondelete="CASCADE")
        batch_op.create_foreign_key(
            None, "blog", ["blog_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("bookmark", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("bookmark_user_id_fkey"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("bookmark_blog_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "user", ["user_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            None, "blog", ["blog_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("comment_blog_id_fkey"), type_="foreignkey")
        batch_op.create_foreign_key(
            None, "blog", ["blog_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("notification_triggered_by_user_id_fkey"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("notification_owner_id_fkey"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("notification_blog_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "user", ["triggered_by_user_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            None, "user", ["owner_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            None, "blog", ["blog_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("userfollowlink", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("userfollowlink_follower_id_fkey"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("userfollowlink_following_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "user", ["follower_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            None, "user", ["following_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("userfollowlink", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("userfollowlink_following_id_fkey"),
            "user",
            ["following_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            batch_op.f("userfollowlink_follower_id_fkey"),
            "user",
            ["follower_id"],
            ["id"],
        )

    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("notification_blog_id_fkey"), "blog", ["blog_id"], ["id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("notification_owner_id_fkey"), "user", ["owner_id"], ["id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("notification_triggered_by_user_id_fkey"),
            "user",
            ["triggered_by_user_id"],
            ["id"],
        )

    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("comment_blog_id_fkey"), "blog", ["blog_id"], ["id"]
        )

    with op.batch_alter_table("bookmark", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("bookmark_blog_id_fkey"), "blog", ["blog_id"], ["id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("bookmark_user_id_fkey"), "user", ["user_id"], ["id"]
        )

    with op.batch_alter_table("blogtaglink", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("blogtaglink_tag_id_fkey"), "tag", ["tag_id"], ["id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("blogtaglink_blog_id_fkey"), "blog", ["blog_id"], ["id"]
        )

    with op.batch_alter_table("bloglikelink", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("bloglikelink_user_id_fkey"), "user", ["user_id"], ["id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("bloglikelink_blog_id_fkey"), "blog", ["blog_id"], ["id"]
        )

    with op.batch_alter_table("blog", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("blog_author_fkey"), "user", ["author"], ["id"]
        )

    # ### end Alembic commands ###
