"""Removed multiple cascade in relationship

Revision ID: 7e35f5bdcea5
Revises: 828f8a6c7558
Create Date: 2025-11-08 12:34:49.539307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e35f5bdcea5'
down_revision: Union[str, Sequence[str], None] = '828f8a6c7558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
