"""Updated index on notificatoin

Revision ID: 8da647cd9680
Revises: 91aaf195bfc4
Create Date: 2025-08-16 12:34:58.684516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8da647cd9680'
down_revision: Union[str, Sequence[str], None] = '91aaf195bfc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('notification_type',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('GENERAL', 'LIKE', 'NEW_BLOG', 'FOLLOW', 'COMMENT', name='notificationtype'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_notification_blog_id'), ['blog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_triggered_by_user_id'), ['triggered_by_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_triggered_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_owner_id'))
        batch_op.drop_index(batch_op.f('ix_notification_blog_id'))
        batch_op.alter_column('notification_type',
               existing_type=sa.Enum('GENERAL', 'LIKE', 'NEW_BLOG', 'FOLLOW', 'COMMENT', name='notificationtype'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###
