"""ll

Revision ID: cb28dbbd932f
Revises: 1a4d1f034c48
Create Date: 2025-08-16 07:45:21.747571

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb28dbbd932f"
down_revision: Union[str, Sequence[str], None] = "1a4d1f034c48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blog", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_public", sa.Boolean(), default=True, nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blog", schema=None) as batch_op:
        batch_op.drop_column("is_public")

    # ### end Alembic commands ###
