"""changed views_count to views

Revision ID: e8af26edbffc
Revises: 5ef3eb2ce6e3
Create Date: 2025-09-04 13:59:26.131913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8af26edbffc'
down_revision: Union[str, Sequence[str], None] = '5ef3eb2ce6e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('comments_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('bookmarks_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('engagement_score', sa.Float(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_blog_engagement_score'), ['engagement_score'], unique=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_comment_created_at'))

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_notification_created_at'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('joined_at',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('joined_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_engagement_score'))
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('engagement_score')
        batch_op.drop_column('views')
        batch_op.drop_column('bookmarks_count')
        batch_op.drop_column('comments_count')
        batch_op.drop_column('likes_count')

    # ### end Alembic commands ###
