name: Run FastAPI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies with uv
        run: uv pip install --system -r pyproject.toml

      - name: Run tests
        env:
          DATABASE_URL: sqlite+aiosqlite:///./test.db
        run: pytest
